# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client_secret', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
