# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 22:32
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clienttoken_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default=core.models.getuuid, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
