# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20160209_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='app_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
