# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20160209_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='registration_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
