# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20160209_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pushconfiguration',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_configuration', to='core.App'),
        ),
    ]
