# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20160214_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='registration_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
